# Generated by Django 5.0.3 on 2024-03-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=255)),
                ("Author", models.CharField(max_length=255)),
                (
                    "Cover",
                    models.CharField(
                        choices=[("HARD", "Hard"), ("SOFT", "Soft")], max_length=8
                    ),
                ),
                ("Inventory", models.PositiveIntegerField()),
                ("Daily_fee", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
