# Generated by Django 5.0.3 on 2024-03-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="Author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Cover",
            new_name="cover",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Daily_fee",
            new_name="daily_fee",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Inventory",
            new_name="inventory",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Title",
            new_name="title",
        ),
    ]
