# Generated by Django 5.0.3 on 2024-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "books_service",
            "0002_rename_author_book_author_rename_cover_book_cover_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.IntegerField(),
        ),
    ]
