# Generated by Django 5.0.3 on 2024-03-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_alter_borrowing_book_id_alter_borrowing_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
    ]
